# Validating Admission Policy
# Name: Prevent containers from escalating privileges
#       Privileged escalation allows a process to change the security context under which its running.
#       In their default state, containers allow privilege escalation.
#       Attackers may use this default behavior to manipulate the application or process and to gain more permissions than they should have.
# Author: Abhijit Jadhav
# Docs: https://hub.datree.io/built-in-rules/prevent-escalating-privileges
# Severity: Low

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "vap-cis-prevent-escalating-privileges-policy-binding"
spec:
  policyName: "vap-cis-prevent-escalating-privileges-policy"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-node-lease
        - kube-public
        - kube-system
        - calico-apiserver
        - calico-system
        - tigera-operator
        - istio-system
