apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: excludesystemnamespaces.k8sautom8.com
spec:
  group: k8sautom8.com
  names:
    kind: ExcludeSystemNamespace
    listKind: ExcludeSystemNamespaceList
    plural: excludesystemnamespaces
    singular: excludesystemnamespaces
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              excludeSystemNamespaces:
                type: array
                items:
                  type: string

