# Validating Admission Policy
# Name: Minimize the admission of privileged hostIPC
#       A container running in the host's IPC namespace can use IPC to interact with processes outside the container.
# Author: Abhijit Jadhav
# Docs: https://hub.armosec.io/docs/c-0215
# Severity: Medium

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "vap-cis-minimize-sharing-host-ipc-namespace-policy-binding"
spec:
  policyName: "vap-cis-minimize-sharing-host-ipc-namespace-policy"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-node-lease
        - kube-public
        - kube-system
        - calico-apiserver
        - calico-system
        - tigera-operator
        - istio-system
