apiVersion: k8sautom8.com/v1
kind: ValidationParameters
metadata:
  name: validation-parameters
spec:
  excludeSystemNamespaces:
    - "kube-node-lease"
    - "kube-public"
    - "kube-system"
    - "calico-apiserver"
    - "calico-system"
    - "tigera-operator"
    - "istio-system"
  allowedRegistries:
    - "registry.k8s.io"
    - "docker.io"
  maxReplicas: 3
